### ISSUE TITLE
トップページ仮実装

### ISSUE THREAD

**Issue by ssssota** [kanko-dori/code-jinro#26]

**Comment by watamoko** [comment]
とりあえずトップページに欲しい機能が何かを教えてください

**Comment by ssssota** [comment]
- [ ] ルール
- [ ] ルーム作成ボタン #44 
- [ ] バグ報告フォーム？ #30 
- [ ] アイキャッチ？
- [ ] リポジトリのリンク？

**Comment by watamoko** [comment]
@ssssota ところでアイキャッチってなんですか

**Comment by ssssota** [comment]
でっかい画像バーン
？「ほーんこういうやつね～」

って感じ？

**Comment by watamoko** [comment]
アイキャッチのイメージがあんまりなので例になるホームページとかあったら貼ってください

**Comment by ssssota** [comment]
https://fontvuer.netlify.app
ワイのfontvuerのページ

**Comment by ssssota** [comment]
アイキャッチはなくてもいいんだけど
内容が殆ど無いようなトップページはあんまりどうかと思ってる

**Comment by watamoko** [comment]
とりあえずimage差し込む欄だけは作っとくわ

**Comment by ssssota** [comment]
貼る画像がないので無理に入れなくてもいいです
それより今あるものを調整してくれると助かる

**Comment by watamoko** [comment]
あっはい
