### ISSUE TITLE
部屋をUIDで管理する

### ISSUE THREAD

**Issue by ssssota** [kanko-dori/code-jinro#44]
#23

**Comment by onsd** [comment]
`部屋を新規作成するボタン` 的なのが必要？

**Comment by ssssota** [comment]
必要なのでトップページに置く予定
トップページに取り掛かってからの登場人物

**Comment by ssssota** [comment]
UIDの生成はfirestoreに任せるのがいいと思うけど
現状の設計だとアクセスしたURLがUIDになるので
どのタイミングでUIDを生成するかみたいなのが問題として残ってる

**Comment by ssssota** [comment]
とりあえず仮実装としてトップページのボタン押したらUIDをフロントで生成して
`history.push(generateRandomRoomID());`とかしておくかなぁ

理想はFunctions叩いてRoom作成させてそのUIDから遷移

**Comment by ssssota** [comment]
これも閉じていいかもしれない

**Comment by ssssota** [comment]
閉じます
