### ISSUE TITLE
.vscode/settings.jsonを作る

### ISSUE THREAD

**Issue by ssssota** [kanko-dori/code-jinro#53]
インデントを揃え隊

**Comment by onsd** [comment]
`formatOnSave` とかもこれでいけるんかな

**Comment by ssssota** [comment]
ESLintがVSCodeに入ってるなら大丈夫ですね

**Comment by ssssota** [comment]
https://github.com/kanko-dori/code-jinro/tree/master/hosting/.vscode

5days ago ...

**Comment by ssssota** [comment]
- [ ] LF
- [ ] indent size (space)
