### ISSUE TITLE
バックエンドの設計を明確化・明文化

### ISSUE THREAD

**Issue by ssssota** [kanko-dori/code-jinro#61]
必要な動作を洗い出し、設計
`/docs`に書き起こす

**Comment by ssssota** [comment]
ref. #68

**Comment by ssssota** [comment]
Functionsを使うことが確定したので積極的にAPIにしていこうかと思う

**Comment by ssssota** [comment]
apiにすることでデータベースのルールガチガチに固めれるな

**Comment by onsd** [comment]
それはありそう

**Comment by onsd** [comment]
database のルールよくわかってないから助かる:pray:
